### PR TITLE
Truncate latencies higher than the maximum allowed value

### PR DESCRIPTION
**Pull request by pingtimeout**
With the recent CO fix, some simulations that rely on Gatling loops (`asLongAs`) and `atOnceUsers` injection broke.  They are cases where we want to get data loaded as fast as possible, but at the expense of unmeasurable latency.

In these cases, there is no predictable throughput.  It is not possible to compensate for coordinated omission.  The CO fix resulted in taking the Gatling user creation time as the send time for every single request.  The maximum allowed latency in `dse-plugin.config` was exceeded and uncaught exceptions killed the plugin threads.

A few other changes will be needed:
* Add some failsafe mechanism that catch exceptions but does not kill threads, in case other errors happen
* Optionally reintroduce CO if the user explicitly requests it, even though I really don't like that idea
* Contribute the HDR code to Gatling so that we do not have to measure latency ourselves, as these corner cases are already handled in gatling

### CODE REVIEW

**Comment by tlasica** [comment]
For the `atOnce` scenario latency is measurable, it is just the scenario where developer should be aware of potential CO issue and it is not a scenario to analyze latency.  But on the other had any latency problem will be visible in the throughput due to the Litt;e's Law IIUC.

**Comment by pingtimeout** [comment]
@tlasica You can now re-enable CO with `-Dgatling.dse.plugin.enable_coordinated_omission`.  I verified locally that it produces the desired effect.

I do not like this at all.  You are effectively saying that you compare latency percentiles that are affected by CO in scenarios where throughput is not similar across runs.  I am 100% sure that it is a huge mistake.  However, I do not want to block your tests during the time we discuss this issue.

I believe that this PR fixes your issues in two different ways:
* Tests that do not have `-Dgatling.dse.plugin.enable_coordinated_omission` will not crash anymore because latency is capped
* Tests that have that parameter will behave like before

**Comment by tlasica** [comment]
@pingtimeout 

Can you show me some test results showing that change from #7 introducing `session.startDate` instead of current time actually solves any problem? I am asking because I feel like `constant` user injection scheme in gatling may actually solve the problem.

Now for the PR:

With change from #7 latency measurement for `atOnce` is completely broken and has to be fixed.
There is no need to introduce `-Dgatling.dse.plugin.enable_coordinated_omission`, there is already such flag and it is called `atOnce`. If you want to keep you `session.startDate` please use user injection style rather then request simulation runners to specify additional flags. 

Regarding latency capping: this is IMO completely invalid for following reasons:
- it makes latency plots e.g. 99,9 completely misleading by hiding real values
- connection between plot values and various internal C* metrics is lost (because client latency is capped while internal C* latency is NOT)

**Comment by pingtimeout** [comment]
> Can you show me some test results showing that change from #7 introducing session.startDate instead of current time actually solves any problem? I am asking because I feel like constant user injection scheme in gatling may actually solve the problem.

No, constant suffers from the same problem.  Here is an example where CO happens:

```scala
import com.datastax.driver.core.PreparedStatement
import com.datastax.driver.dse.{DseCluster, DseSession}
import com.datastax.gatling.plugin.CqlPredef._
import io.gatling.core.Predef.{scenario, _}
import io.gatling.core.scenario.Simulation

import scala.concurrent.duration._

class ExampleDseSimulation extends Simulation {
  private val cluster = DseCluster.builder().addContactPoint("127.0.0.1").build()
  private val session: DseSession = cluster.connect()
  private val statement: PreparedStatement = session.prepare("SELECT now() from system.local")

  private def buildSlowFeeder(): Feeder[String] = {
    Stream
      .from(0)
      .map { _ =>
        Thread.sleep(1000)
        Map("foo" -> "bar")
      }
      .iterator
  }

  val scn = scenario("CQL")
    .feed(buildSlowFeeder())
    .exec(cql("Select date").executeNamed(statement))

  setUp(scn.inject(constantUsersPerSec(1).during(10 seconds))
    .protocols(dseProtocolBuilder.session(session)))

  after(cluster.close())
}
```

Running it without the CO fix gives you latency close to the millisecond.  The delay introduced by building the feeder is not taken into account.  Whereas if you run with the CO fix, you will see latencies reported around 1 second.

> There is no need to introduce -Dgatling.dse.plugin.enable_coordinated_omission, there is already such flag and it is called atOnce. If you want to keep you session.startDate please use user injection style rather then request simulation runners to specify additional flags.

What do you mean by _user injection style_?

> Regarding latency capping: this is IMO completely invalid for following reasons:
> [...]

You are missing the point.  The user explicitly asks for a maximum latency of `x`.  The test runs for a few hours and a latency higher than `x` is spotted.  Cassandra will report it.  Gatling will report nothing because it will crash.  Several hours are lost.

Is it better than truncating the value and printing `ERROR` messages?  Definitely not.

**Comment by tlasica** [comment]
@pingtimeout so please confirm:

The change in how we measure latency (suing `session.startDate`) will fire only for client side issues (like feeder being too slow?). For server side issue `constant` user injection rate (assuming feeder is fast enough) will guard us from CO?

**Comment by mike-tr-adamson** [comment]
I'm not really interested in re-enabling CO for the `atOnce` simulations. We have already established (and I thought agreed) that latency times from these simulation types were meaningless because of CO.

I really would like to see the primary part of this fix in asap though because [#7](https://github.com/datastax/gatling-dse-plugin/pull/7) has broken all tests that use `atOnce` for fast data loading simulations.

**Comment by tlasica** [comment]
I will run some simulation to verify what I mean:
For me completely invalid latencies are doing more harm that latencies
suffering from CO.

On Mon, Jul 9, 2018 at 3:22 PM Mike Adamson <notifications@github.com>
wrote:

> I'm not really interested in re-enabling CO for the atOnce simulations.
> We have already established (and I thought agreed) that latency times from
> these simulation types were meaningless because of CO.
>
> I really would like to see the primary part of this fix in asap though
> because #7
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_datastax_gatling-2Ddse-2Dplugin_pull_7&d=DwMFaQ&c=adz96Xi0w1RHqtPMowiL2g&r=zKQEy9QZ7WAJca7z9R4z_T7_hf7tJ224pJ3vWdfaNUM&m=DYrHn6Nd1A8WvSE0aLdD7AHoM8dceA52WoLlVBZvR0U&s=32EKbBsZ99lR0tNG2ADdIvIPV76aTEQXNYCxu49grJY&e=>
> has broken all tests that use atOnce for fast data loading simulations.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_datastax_gatling-2Ddse-2Dplugin_pull_8-23issuecomment-2D403476664&d=DwMFaQ&c=adz96Xi0w1RHqtPMowiL2g&r=zKQEy9QZ7WAJca7z9R4z_T7_hf7tJ224pJ3vWdfaNUM&m=DYrHn6Nd1A8WvSE0aLdD7AHoM8dceA52WoLlVBZvR0U&s=XuU-S7F5BUu39bd5BVts3UGMweXx4Uor0M3XyaYYQEk&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABdqzTqulo8xJXt3Iw040ICkhzgaQ70uks5uE1kkgaJpZM4VFSDP&d=DwMFaQ&c=adz96Xi0w1RHqtPMowiL2g&r=zKQEy9QZ7WAJca7z9R4z_T7_hf7tJ224pJ3vWdfaNUM&m=DYrHn6Nd1A8WvSE0aLdD7AHoM8dceA52WoLlVBZvR0U&s=yIyCWmTbO5iw3L6a9uVnZ4FhMNSA1MsbCk3dE5Pz-2Y&e=>
> .
>


--

**Comment by tlasica** [comment]
Especially in case of a scenario when we explicitly (by using `atOnce``)
say we know this is not a latency measurement.


On Mon, Jul 9, 2018 at 3:29 PM Tomasz Lasica <tomasz.lasica@datastax.com>
wrote:

> I will run some simulation to verify what I mean:
> For me completely invalid latencies are doing more harm that latencies
> suffering from CO.
>
> On Mon, Jul 9, 2018 at 3:22 PM Mike Adamson <notifications@github.com>
> wrote:
>
>> I'm not really interested in re-enabling CO for the atOnce simulations.
>> We have already established (and I thought agreed) that latency times from
>> these simulation types were meaningless because of CO.
>>
>> I really would like to see the primary part of this fix in asap though
>> because #7
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_datastax_gatling-2Ddse-2Dplugin_pull_7&d=DwMFaQ&c=adz96Xi0w1RHqtPMowiL2g&r=zKQEy9QZ7WAJca7z9R4z_T7_hf7tJ224pJ3vWdfaNUM&m=DYrHn6Nd1A8WvSE0aLdD7AHoM8dceA52WoLlVBZvR0U&s=32EKbBsZ99lR0tNG2ADdIvIPV76aTEQXNYCxu49grJY&e=>
>> has broken all tests that use atOnce for fast data loading simulations.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_datastax_gatling-2Ddse-2Dplugin_pull_8-23issuecomment-2D403476664&d=DwMFaQ&c=adz96Xi0w1RHqtPMowiL2g&r=zKQEy9QZ7WAJca7z9R4z_T7_hf7tJ224pJ3vWdfaNUM&m=DYrHn6Nd1A8WvSE0aLdD7AHoM8dceA52WoLlVBZvR0U&s=XuU-S7F5BUu39bd5BVts3UGMweXx4Uor0M3XyaYYQEk&e=>,
>> or mute the thread
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABdqzTqulo8xJXt3Iw040ICkhzgaQ70uks5uE1kkgaJpZM4VFSDP&d=DwMFaQ&c=adz96Xi0w1RHqtPMowiL2g&r=zKQEy9QZ7WAJca7z9R4z_T7_hf7tJ224pJ3vWdfaNUM&m=DYrHn6Nd1A8WvSE0aLdD7AHoM8dceA52WoLlVBZvR0U&s=yIyCWmTbO5iw3L6a9uVnZ4FhMNSA1MsbCk3dE5Pz-2Y&e=>
>> .
>>
>
>
> --
>
>
>

--

**Comment by tlasica** [comment]
@pingtimeout 

> What do you mean by user injection style?

`atOnce` or `constant`



> You are missing the point. The user explicitly asks for a maximum latency of x. The test runs for a few hours and a latency higher than x is spotted. Cassandra will report it. Gatling will report nothing because it will crash. Several hours are lost.

This all sounds good if latency is measured correct, if it is not measured correctly - due to #7 with atOnce -then after test duration > max latency duration every request will be longer than x. That is the problem.

**Comment by jakubzytka** [comment]
latency measurements of `atOnceUsers` simulations are not meaningless. They just mean service time.
What's wrong with that? This is the latency measurement that _by definition_ `atOnceUsers` gives you.

Why should we be special in the whole world? Why everybody else is fine with `atOnce` measuring service time, but we should have some weird semantics?

I don't see that the fact that service time is not practical for measuring client latency values is relevant here. 
Especially that service time is not useless _per se_, but can tell you whether you're fighting against general slowness (=> optimize code) or occasional hiccups (=> find out why sth gets stuck)

**Comment by nitsanw** [comment]
2 cents worth: "The only latency that is worth measuring in a variable throughput scenario is the wall-clock time, and therefore the average latency."

The term latency is rather loaded, but if we break it down:
`response-time = queue-time + service-time`

I think there's scenarios where people are interested in one and not the other. Problems arise when we confuse one for the other (e.g. claiming service-time == response-time).

IIUC in the `atOnce` scenario there's 2 ways of interpreting the intent:
 - We have a response-time for the whole set of operations which need to happen `atOnce`
 - We have a service-time for each operation in the set. We don't have an interest in each operation response-time, we're not scripting each operation launch to a particular time.

Using service-time as a guideline for system responsiveness leads to many a sad panda, but may be interesting to people for other reasons. It's a valid metric AS LONG AS IT IS NOT REPORTED AS RESPONSE TIME.

**Comment by tlasica** [comment]
@nitsanw  thanks for 2 :cents:, I thikn it is essential to undestand that with `atOnce` we are indeed not aiming at 
> Using service-time as a guideline for system responsiveness
For system responsiveness we measure using `constant` or better `staircase` load when #7 works fine (but it also includes building the feed time after #7 which I am not that sure is what we want to include)

**Comment by tlasica** [comment]
@pingtimeout please take a look at this results:
http://fallout.datastax.lan/tests/ui/tomasz.lasica@datastax.com/PR8/01b4c912-3e29-4d12-a6ad-78b04ddfa404/artifacts/client/performance-report.html?stats=undefined&metric=Ops_Sec&operation=INSERT_ROW__writes__int_ok&smoothing=1&show_aggregates=true&xmin=0&xmax=1682576533.9&ymin=0&ymax=10999894.4

Will it change to good if truncated and not `-Denabled_co` flag is used?

**Comment by tlasica** [comment]
@pingtimeout  can you prepare a `dse-benchmarks` branch to test this PR?

**Comment by nitsanw** [comment]
@pingtimeout @tlasica the graphs timeline indicates an issue with the log recording. From one of the logs:
```
#[StartTime: 1531146.176 (seconds since epoch), Sun Jan 18 17:19:06 UTC 1970]
"StartTimestamp","Interval_Length","Interval_Max","Interval_Compressed_Histogram"
1531146176.000,...
```
From benchmarks I use (gatling too):
```
#[StartTime: 1530875813.148 (seconds since epoch), Fri Jul 06 11:16:53 UTC 2018]
"StartTimestamp","Interval_Length","Interval_Max","Interval_Compressed_Histogram"
1530875873.000,...
```
Note the new StartTime appears to have been converted once too many. Also note in the old version the first histogram is from **before** the start of the log ... :(   but that at least seems to somehow work with the graphs.

**Comment by pingtimeout** [comment]
@tlasica here you go: branch `use-snapshot` in dse-benchmarks https://github.com/riptano/dse-benchmarks/commit/a70a9f03ad60339a4f62f44658fa227336084e35

**Comment by tlasica** [comment]
Thanks!

On Mon, Jul 9, 2018 at 4:56 PM Pierre Laporte <notifications@github.com>
wrote:

> @tlasica
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_tlasica&d=DwMCaQ&c=adz96Xi0w1RHqtPMowiL2g&r=zKQEy9QZ7WAJca7z9R4z_T7_hf7tJ224pJ3vWdfaNUM&m=Rz_iHcXcMWQgb3-VDzTKCuLOXTNNUtiLVRHJ3czs3eM&s=B5X672cErpdTsASIokTGyZvflYENn9J3EcIspY0m-uk&e=>
> here you go: branch use-snapshot in dse-benchmarks riptano/dse-benchmarks@
> a70a9f0
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_riptano_dse-2Dbenchmarks_commit_a70a9f03ad60339a4f62f44658fa227336084e35&d=DwMCaQ&c=adz96Xi0w1RHqtPMowiL2g&r=zKQEy9QZ7WAJca7z9R4z_T7_hf7tJ224pJ3vWdfaNUM&m=Rz_iHcXcMWQgb3-VDzTKCuLOXTNNUtiLVRHJ3czs3eM&s=edlz5v487_PryFa2xk7I9Ea6sHYfDxuW-76dFDJ8Dzk&e=>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_datastax_gatling-2Ddse-2Dplugin_pull_8-23issuecomment-2D403507918&d=DwMCaQ&c=adz96Xi0w1RHqtPMowiL2g&r=zKQEy9QZ7WAJca7z9R4z_T7_hf7tJ224pJ3vWdfaNUM&m=Rz_iHcXcMWQgb3-VDzTKCuLOXTNNUtiLVRHJ3czs3eM&s=8fG7wqdErwNGom8fZDxo7bDQ_Up6L__j2009_UgKwaw&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABdqzT641zzgW08Kvpn8ELq-5FPfe70l9Dks5uE28JgaJpZM4VFSDP&d=DwMCaQ&c=adz96Xi0w1RHqtPMowiL2g&r=zKQEy9QZ7WAJca7z9R4z_T7_hf7tJ224pJ3vWdfaNUM&m=Rz_iHcXcMWQgb3-VDzTKCuLOXTNNUtiLVRHJ3czs3eM&s=32QmusUlymlmev2Dm8Zi0vlDU3E6AOxB0vy6IOZlyd8&e=>
> .
>


--

**Comment by tlasica** [comment]
Also, `-Dgatling.dse.plugin.enable_coordinated_omission` name is not right, it is not that we enable it, we more allow it. And I personally like more sth like `-Dgatling.dse.plugin.use_service_time`, becasue proposed name sounds to me like `enable_flat_tire`.

**Comment by pingtimeout** [comment]
Changed the name to `gatling.dse.plugin.measure_service_time`.  @tlasica can you confirm you are ok with merging this PR now?

**Comment by pingtimeout** [comment]
Also, I :ninja: fixed the hdr histogram comment

**Comment by tlasica** [comment]
Run from yesterday using `use-snapshot` branch looks good:
http://fallout.datastax.lan/tests/ui/tomasz.lasica@datastax.com/PR8/e19af365-0726-473e-984a-cbd2970b7499/artifacts/client/performance-report.html?stats=undefined&metric=Ops_Sec&operation=INSERT_ROW__writes__int_ok&smoothing=1&show_aggregates=true&xmin=0&xmax=1039.86&ymin=0&ymax=58095.4
with system variable set so I think we can merge this one.

Please remember to send comprehensive message:
- what was broken
- how to fix it

I have not tried to set env var from simulation code but it should work

**Comment by pingtimeout** [comment]
Triggered a release so that you don't need to use the snapshot version

**Comment by nitsanw** [comment]
I still see the StartTime issue here: http://fallout.datastax.lan/tests/ui/tomasz.lasica@datastax.com/PR8/e19af365-0726-473e-984a-cbd2970b7499/artifacts/client/node0/gatling/createschema-1531155578107/hgrms/tags/SELECT_____WITH_solr_query_int_ok.hgrm

**Comment by nitsanw** [comment]
@tlasica "I hope this issue will teach us something :-)"
Time is an illusion, and lunch time doubly so.
;-)

**Comment by tlasica** [comment]
@nitsanw what you see is because simulation first create schema and runs some test query to make sure that search index is correctly created. This simulation (Schema) did not get the flag.
This is the code: https://github.com/riptano/dse-benchmarks/blob/master/src/test/scala/search/dsp4800/CreateSchema.scala#L62-L75

**Comment by tlasica** [comment]
Now about learning, I already mentioned it to Pierre.
In many good teams there is an attitude for continuous improvement, which I believe is our case.
In many from those teams there is a retrospective time when we can discuss how to improve.
In this case I would like to know:
a) if the design (to use session.startTime) was discussed before implementation
b) what tests were run to confirm #7 works correctly

What I observed few times in Datastax is lack of design review for larger code changes in favor of (rather difficult on large PRs) code reviews done after 1 person did the coding. I understand it is harder in a remote environment.

**Comment by nitsanw** [comment]
@pingtimeout I thought this https://github.com/datastax/gatling-dse-plugin/pull/8/commits/8dfa8179733cc908e5f47c08e644476fbe13938c was supposed to fix the issue?

**Comment by tlasica** [comment]
@pingtimeout could you please comment on latest @nitsanw question?

**Comment by tlasica** [comment]
> By creating only n users upfront, you are currently twisting this model to have a behavior comparable to cassandra-stress. But this also completely changes the injection model.

I am not sure, I think we more twist gatling plugin model than gatling model itself.

> I understand why you are doing this. But in the future, I think you should switch to DSBulk, which is precisely made for data ingestion.

Search scenarios need not only lot of data but - most of all - valuable data as they are used to test indexing which is highly data depenendent. That is why we are using Scala to generate meanigful (in terms of indexing) data. We can of course generate data in python to CSV and then pipe it to DSBulk.

**Comment by pingtimeout** [comment]
You can add a class in your simulation with a `main` method that prints your CSV data in stdout.  That way you have the same data generation engine between your data loading phase and your read query phases without having any CSV file to store.

**Comment by tlasica** [comment]
sure, but tell me why i should make things more complex?

**Pull request merged**
